// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UnturnedAssets.Database;

namespace UnturnedAssets.Migrations
{
    [DbContext(typeof(UnturnedAssetsDbContext))]
    partial class UnturnedAssetsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("UnturnedAssets.Database.Models.ItemAsset", b =>
                {
                    b.Property<ushort>("Id")
                        .HasColumnType("smallint unsigned");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("GUID")
                        .HasColumnType("varchar CHARACTER SET utf8mb4")
                        .HasMaxLength(128);

                    b.Property<string>("Description")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("Rarity")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .HasColumnType("smallint CHARACTER SET utf8mb4");
                    
                    b.Property<string>("AssetType")
                        .HasColumnType("text CHARACTER SET utf8mb4");

                    b.Property<string>("Path")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("GUID");

                    b.ToTable("UnturnedAssets_ItemAssets");
                });

            modelBuilder.Entity("UnturnedAssets.Database.Models.VehicleAsset", b =>
                {
                    b.Property<ushort>("VehicleId")
                        .HasColumnType("smallint unsigned");

                    b.Property<string>("VehicleName")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("GUID")
                        .HasColumnType("varchar CHARACTER SET utf8mb4")
                        .HasMaxLength(128);

                    b.HasKey("GUID");

                    b.ToTable("UnturnedAssets_VehicleAssets");
                });
        }
    }
}
